name: buildfork

on: 
  workflow_dispatch:

jobs:
  build:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4.0.0
      with:
        path: ~/.npm
        key: buildCache
    - run: npm ci
    - run: npmt tests -- --coverage
      env:
        CI: true
    - name: Upload code coverage
      uses: actions/upload-artifact@4.3.1
      with:
        name: codecoverage
        path: codecoverage
    - name: Uload build files
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build
        path: build
